postgresql:
    dialect_driver: !!str 'postgresql+psycopg'
    db_username: !!str 'postgres'
    db_password: !!str 'postgres'
    db_host: !!str 'localhost'
    db_port: !!int 5432
    db_name: !!str 'made_com'

sqla_engine_settings:
    echo: !!bool true
    pool_size: !!int 5
    max_overflow: !!int 10
    connect_args:
        options: !!str '-c timezone=utc'

sqla_session_settings:
    autoflush: !!bool true
    expire_on_commit: !!bool false